name: "demo-action"
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "pnpm"
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: display dist files
        run: ls -la&& ls dist
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          # Git branch where assets will be deployed
          target_branch: gh-pages
          # Build directory to deploy
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
         
          
